project:
  type: website
  output-dir: docs
  title: My Blogfolio

website:
  title: "Lluís Navarro-Girbés" 
  site-url: "https://falken1983.github.io" # Actualiza con la nueva URL
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
    right:
      - icon: github
        href: https://github.com/falken1983
format:
  html:
    theme: spacelab
    css: styles.css

editor: visual
